account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('login', views.UserLogin.as_view(), name='user_login'),
    path('otplogin', views.OtpLoginView.as_view(), name='user_otp_login'),
    path('checkotp', views.CheckOtpView.as_view(), name='check_otp'),
    path('logout', views.user_logout, name='user_logout'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('detail', views.CartDetailView.as_view(), name='cart_detail'),
    path('add/<int:pk>', views.CartAddView.as_view(), name='cart_add'),
    path('delete/<str:id>', views.CardDeleteView.as_view(), name='cart_delete'),
    path('order/<int:pk>', views.OrderDetailView.as_view(), name='order_detail'),
    path('order/add', views.OrderCreationView.as_view(), name='order_creation'),
    path('applydiscount/<int:pk>', views.ApplyDiscountView.as_view(), name='apply_discount'),
    path('sendrequest/<int:pk>', views.SendRequestView.as_view(), name='send_request'),
]

multi_shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('account/', include("account.urls")),
    path('products/', include("product.urls")),
    path('cart/', include("cart.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from account.models import User
from product.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='order')
    total_price = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)

    def __str__(self):
        return self.user.phone


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='items')
    size = models.CharField(max_length=12)
    color = models.CharField(max_length=12)
    quantity = models.SmallIntegerField()
    price = models.PositiveIntegerField()
    address = models.TextField(blank=True, null=True)


class DiscountCode(models.Model):
    name = models.CharField(max_length=10, unique=True)
    discount = models.SmallIntegerField(default=0)
    quantity = models.SmallIntegerField(default=1)

    def __str__(self):
        return self.name

cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from account.models import Address
from . import cart_module
from product.models import Product
from .cart_module import Cart
from .models import Order, OrderItem, DiscountCode


class CartDetailView(View):
    def get(self, request):
        cart = cart_module.Cart(request)
        return render(request, "cart/cart_detail.html", {'cart': cart})


class CartAddView(View):
    def post(self, request, pk):
        product = Product.objects.get(id=pk)
        size, color, quantity = (request.POST.get("size", 'empty'),
                                 request.POST.get("color", 'empty'), request.POST.get('quantity'))
        cart = cart_module.Cart(request)
        cart.add(product, quantity, color, size)
        return redirect('cart:cart_detail')


class CardDeleteView(View):
    def get(self, request, id):
        cart = Cart(request)
        cart.delete(id)
        return redirect('cart:cart_detail')


class OrderDetailView(LoginRequiredMixin, View):
    def get(self, request, pk):
        order = get_object_or_404(Order, id=pk)
        return render(request, 'cart/order_detail.html', {'order': order})


class OrderCreationView(LoginRequiredMixin, View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user, total_price=cart.total())
        for item in cart:
            OrderItem.objects.create(
                order=order,
                product=item['product'],
                color=item['color'],
                size=item['size'],
                quantity=item['quantity'],
                price=item['price'])
        cart.remove_cart()
        return redirect('cart:order_detail', order.id)


class ApplyDiscountView(LoginRequiredMixin, View):
    def post(self, request, pk):
        code = request.POST.get('discount_code')
        order = get_object_or_404(Order, id=pk)
        discount_code = get_object_or_404(DiscountCode, name=code)
        if discount_code == 0:
            return redirect('cart:order_detail', order.id)

        order.total_price -= order.total_price * discount_code.discount / 100
        order.save()
        discount_code.quantity -= 1
        discount_code.save()
        return redirect('cart:order_detail', order.id)


# ? sandbox merchant
# if settings.SANDBOX:
#     sandbox = 'sandbox'
# else:
#     sandbox = 'www'
#
ZP_API_REQUEST = f"https://api.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = f"https://api.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = f"https://www.zarinpal.com/pg/StartPay/"
amount = 1000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
phone = 'YOUR_PHONE_NUMBER'  # Optional
# Important: need to edit for realy server.
CallbackURL = 'http://127.0.0.1:8080/cart/verify/'


class SendRequestView(View):
    def post(self, request, pk):
        order = get_object_or_404(Order, id=pk, user=request.user)
        address = get_object_or_404(Address, id=request.POST.get('address'))
        order.address = f'{address.address} - {address.phone} - {address.email}'
        order.save()
        return HttpResponse(request.POST.get('address'))
        # req_data = {
        #     "MerchantID": settings.MERCHANT,
        #     "Amount": order.total_price,
        #     "Description": description,
        #     "Phone": phone,
        #     "CallbackURL": CallbackURL,
        # }
        # data = json.dumps(req_data)
        # # set content length by data
        # headers = {'content-type': 'application/json', 'content-length': str(len(req_data))}
        # try:
        #     response = requests.post(ZP_API_REQUEST, data=data, headers=headers, timeout=10)
        #
        #     if response.status_code == 200:
        #         response = response.json()
        #         if response['Status'] == 100:
        #             return {'status': True, 'url': ZP_API_STARTPAY + str(response['Authority']),
        #                     'authority': response['Authority']}
        #         else:
        #             return {'status': False, 'code': str(response['Status'])}
        #     return response
        #
        # except requests.exceptions.Timeout:
        #     return {'status': False, 'code': 'timeout'}
        # except requests.exceptions.ConnectionError:
        #     return {'status': False, 'code': 'connection error'}

cart/templates/cart/cart_detail.html
{% extends "base.html" %}
{% load  static %}

{% block main %}
    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Color</th>
                            <th>Size</th>
                            <th>Total</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                     {% for item in cart %}

                         <tr>
                            <td class="align-middle"><img src="{{ item.product.image.url }}" alt="" style="width: 50px;"></td>
                            <td class="align-middle">{{ item.product.title }}</td>
                            <td class="align-middle">${{ item.price }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size }}</td>
                            <td class="align-middle">${{ item.total  }}</td>
                            <td class="align-middle"><a href="{% url 'cart:cart_delete' item.unique_id %}" ><i class="fa fa-times"></i></a></td>
                        </tr>

                      {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>Subtotal</h6>
                            <h6>$150</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">Shipping</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ cart.total }}</h5>
                        </div>
                        <a href="{% url 'cart:order_creation' %}" class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}

cart/templates/cart/order_detail.html
{% extends "base.html" %}
{% load  static %}

{% block main %}
    <!-- Cart Start -->
    <div class="container-fluid">
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                    <tr>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Color</th>
                        <th>Size</th>
                        <th>Total</th>
                    </tr>
                    </thead>
                    <tbody class="align-middle">
                    {% for item in order.items.all %}

                        <tr>
                            <td class="align-middle"><img src="{{ item.product.image.url }}" alt=""
                                                          style="width: 50px;"></td>
                            <td class="align-middle">{{ item.product.title }}</td>
                            <td class="align-middle">${{ item.price }}</td>
                            <td class="align-middle">{{ item.quantity }}</td>
                            <td class="align-middle">{{ item.color }}</td>
                            <td class="align-middle">{{ item.size }}</td>
                            <td class="align-middle">${{ item.total }}</td>

                        </tr>

                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" method="post" action="{% url 'cart:apply_discount' order.id %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="discount_code" class="form-control border-0 p-4"
                               placeholder="Discount  Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span>
                </h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2"></div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>Total</h5>
                            <h5>${{ order.total_price }}</h5>
                        </div>
                    </div>
                </div>
                {% if request.user.addresses.all %}
                    <form action="{% url 'cart:send_request' order.id %}" method="post">
                        {% csrf_token %}
                        <select name="address" class="form-control" aria-label="Default select example">
                            {% for address in request.user.addresses.all %}
                                <option value="{{ address.id }}">{{ address.address }}</option>
                            {% endfor %}
                        </select>
                        <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}"
                           class="btn btn-block btn-primary font-weight-bold my-3 py-3"> Add another Address</a>

                        <button type="submit" class="btn btn-block btn-success font-weight-bold my-3 py-3">Pay</button>

                    </form>
                {% else %}
                    <a href="{% url 'account:add_address' %}?next={% url 'cart:order_detail' order.id %}"
                       class="btn btn-block btn-primary font-weight-bold my-3 py-3">You dont any Address, Add One</a>
                {% endif %}

            </div>
        </div>
    </div>
    <!-- Cart End -->

{% endblock %}